# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: tr7zw
          template: classic
          base: header, activity, community, repositories
          config_timezone: Europe/Berlin
          
          # Plugins
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_ignored: CSS, HTML, PHP
          plugin_languages_limit: 8
          plugin_languages_threshold: 2%
          plugin_stargazers: yes
          plugin_stargazers_charts_type: graph
          plugin_stargazers_days: 0
          plugin_calendar: yes
          plugin_calendar_limit: 4
          plugin_lines: yes
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_notable_types: commit, issue, pull-request
          plugin_people: yes
          plugin_people_limit: 28
          plugin_people_size: 28
          plugin_people_types: followers, following